packages:
  - '@internal/*'
  - '@kv-design/*'
  - 'design-tokens'

catalog:
  # Design System Dependencies
  '@digdir/designsystemet': 1.11.0
  '@digdir/designsystemet-css': '^1.11.0'
  '@digdir/designsystemet-react': '^1.11.0'
  '@digdir/designsystemet-types': '^1.11.0'

  # React & React DOM
  'react': '^19.2.0'
  'react-dom': '^19.2.0'
  '@types/react': '^19.2.5'
  '@types/react-dom': '^19.2.3'

  # Build & Development Tools
  vite: ^7.3.1
  vitest: '^4.0.17'
  '@vitejs/plugin-react': '^5.1.1'
  '@vitest/browser-playwright': '^4.0.17'
  '@vitest/coverage-v8': '^4.0.17'
  vite-plugin-dts: ^4.5.4
  vite-tsconfig-paths: ^6.0.5

  # Storybook
  'storybook': '^10.2.8'
  '@storybook/react-vite': '^10.2.8'
  '@storybook/addon-a11y': '^10.2.8'
  '@storybook/addon-docs': '^10.2.8'
  '@storybook/addon-onboarding': '^10.2.8'
  '@storybook/addon-vitest': '^10.2.8'
  "@nx/storybook": 22.5.1
  '@chromatic-com/storybook': '^5.0.1'
  'chromatic': '^13.3.5'
  'eslint-plugin-storybook': '^10.2.8'

  # Linting & Code Quality
  'eslint': '^9.39.2'
  '@eslint/js': '^9.39.2'
  '@eslint/compat': ^2.0.1
  '@nx/eslint': 22.5.1
  '@nx/eslint-plugin': 22.5.1
  eslint-plugin-import: ^2.32.0
  eslint-plugin-jsx-a11y: ^6.10.2
  'eslint-plugin-react-hooks': '^7.0.1'
  'eslint-plugin-react-refresh': '^0.4.24'
  madge: ^8.0.0

  # Testing
  'playwright': '^1.57.0'

  # TypeScript
  'typescript': '^5.9.3'
  '@typescript/native-preview': 7.0.0-dev.20260126.1
  typescript-eslint: ^8.53.1
  '@typescript-eslint/eslint-plugin': ^8.53.1
  '@typescript-eslint/parser': ^8.53.1
  tslib: ^2.8.1


  "@types/node": ^24.10.13
  '@types/ramda': ^0.31.1
  "@nx/vite": "22.5.1"
  "@nx/web": "22.5.1"
  "@vitest/ui": "^4.0.17"
  "jiti": "2.4.2"
  "nx": "22.5.1"
  ramda: ^0.32.0

  rimraf: ^6.1.2
  '@types/micromatch': ^4.0.10
  '@types/yargs': ^17.0.35
  micromatch: ^4.0.8
  tsx: ^4.21.0
  yargs: ^18.0.0
  autoprefixer: ^10.4.23
  cssnano: ^7.1.2
  postcss: ^8.5.6
  postcss-cli: ^11.0.1
  postcss-easy-import: ^4.0.0
  postcss-load-config: ^6.0.1
  postcss-nesting: ^14.0.0

packageExtensions:
  '@navikt/aksel-icons':
    peerDependencies:
      '@types/react': ^18.3.11 || ^19.0.0
      react: ^18.3.1 || ^19.0.0
    peerDependenciesMeta:
      '@types/react':
        optional: true
      react:
        optional: true

onlyBuiltDependencies:
  - esbuild

useNodeVersion: 24.13.0
