packages:
  - '@kv-design/*'
  - 'design-tokens'

catalog:
  # Design System Dependencies
  '@digdir/designsystemet-css': '^1.11.0'
  '@digdir/designsystemet-react': '^1.11.0'
  '@digdir/designsystemet-types': '^1.11.0'

  # React & React DOM
  'react': '^19.2.0'
  'react-dom': '^19.2.0'
  '@types/react': '^19.2.5'
  '@types/react-dom': '^19.2.3'

  # Build & Development Tools
  vite: ^7.3.1
  vitest: '^4.0.17'
  '@vitejs/plugin-react': '^5.1.1'
  '@vitest/browser-playwright': '^4.0.17'
  '@vitest/coverage-v8': '^4.0.17'

  # Storybook
  'storybook': '^10.2.8'
  '@storybook/react-vite': '^10.2.8'
  '@storybook/addon-a11y': '^10.2.8'
  '@storybook/addon-docs': '^10.2.8'
  '@storybook/addon-onboarding': '^10.2.8'
  '@storybook/addon-vitest': '^10.2.8'
  '@storybook/test': '^10.2.8'
  '@chromatic-com/storybook': '^5.0.1'
  'chromatic': '^13.3.5'
  'eslint-plugin-storybook': '^10.2.8'

  # Linting & Code Quality
  'eslint': '^9.39.1'
  '@eslint/js': '^9.39.1'
  'eslint-plugin-react-hooks': '^7.0.1'
  'eslint-plugin-react-refresh': '^0.4.24'

  # Testing
  'playwright': '^1.57.0'

  # TypeScript
  'typescript': '^5.9.3'

onlyBuiltDependencies:
  - esbuild
