// Checks that Controls work on every component docs page. Fails if:
// 1. a component MDX page has no <Controls /> block, or
// 2. the Preview story has a render function that ignores args, so the controls do nothing.
// Our MDX pages replace the autogenerated docs page, so Controls only show up where we add them.
import { globSync, readFileSync } from 'node:fs';

// 1. MDX pages without <Controls />

const mdxWithoutControls = globSync('src/components/**/*.mdx').filter(
  (file) => !readFileSync(file, 'utf8').includes('<Controls'),
);

if (mdxWithoutControls.length > 0) {
  console.error('These MDX files are missing <Controls />. Add it right after <Primary />:');
  mdxWithoutControls.forEach((file) => console.error(`  ${file}`));
  process.exit(1);
}

// 2. Preview stories that ignore args.
// <Primary /> and <Controls /> on the MDX page use the Preview story. If its render function
// doesn't pass args on to the component, changing a control does nothing.
// A Preview without a render function is fine: Storybook then passes args on by itself.

// Returns the source code of the Preview story: from `export const Preview: Story = {`
// to the first line that is just `};`. Returns undefined if the file has no such story.
const getPreviewStory = (file: string) =>
  readFileSync(file, 'utf8').match(/export const Preview: Story = \{[\s\S]*?\n\};/)?.[0];

// __screenshots__ has folders named after the story files (e.g. Alert.stories.tsx/),
// so only keep files.
const storyFiles = globSync('src/components/**/*.stories.tsx', { withFileTypes: true })
  .filter((entry) => entry.isFile())
  .map((entry) => `${entry.parentPath}/${entry.name}`);

const storiesIgnoringArgs = storyFiles.filter((file) => {
  const preview = getPreviewStory(file);
  const hasRenderFunction = preview?.includes('render:');
  const passesArgs = preview?.includes('{...args}');
  return hasRenderFunction && !passesArgs;
});

if (storiesIgnoringArgs.length > 0) {
  console.error(
    'The Preview story in these files has a render function that ignores args. Spread {...args} onto the component:',
  );
  storiesIgnoringArgs.forEach((file) => console.error(`  ${file}`));
  process.exit(1);
}

console.log('All component MDX files include <Controls />, and all Preview stories pass args on.');
