import { fileURLToPath } from 'node:url';
import { defineConfig } from 'oxlint';
import baseConfig, { importOrderRules } from '../../oxlint.config.ts';

// Nested configs replace (not merge with) the root config, so we spread the
// base config here. `options` is only allowed in the root config.
const { options: _options, overrides: baseOverrides = [], ...base } = baseConfig;

// Shared restricted imports across the repo
const commonRestrictedImports = [
  {
    group: ['@kv-designsystem/react', '@kv-designsystem/react/*'],
    message: 'Do not import from @kv-designsystem/react. Use relative paths instead.',
  },
  { group: ['**/dist/*'], message: 'Do not import from the dist directory.' },
  {
    group: ['**/node_modules/*'],
    message: 'Do not import from the node_modules directory.',
  },
];

export default defineConfig({
  ...base,
  ignorePatterns: [
    'src/components', // TODO: remove this to when components are ready to be linted
  ],
  overrides: [
    // Previously provided by the Nx `flat/react` config
    {
      files: ['**/*.{ts,tsx,cts,mts,js,jsx,cjs,mjs}'],
      plugins: ['import', 'typescript', 'react', 'jsx-a11y'],
      env: { browser: true, es2016: true, jest: true, node: true },
      rules: {
        'array-callback-return': 'warn',
        eqeqeq: ['warn', 'smart'],
        'no-caller': 'warn',
        'no-cond-assign': ['warn', 'except-parens'],
        'no-const-assign': 'warn',
        'no-control-regex': 'warn',
        'no-delete-var': 'warn',
        'no-dupe-keys': 'warn',
        'no-duplicate-case': 'warn',
        'no-empty-character-class': 'warn',
        'no-empty-pattern': 'warn',
        'no-eval': 'warn',
        'no-ex-assign': 'warn',
        'no-extend-native': 'warn',
        'no-extra-bind': 'warn',
        'no-extra-label': 'warn',
        'no-fallthrough': 'warn',
        'no-func-assign': 'warn',
        'no-implied-eval': 'warn',
        'no-invalid-regexp': 'warn',
        'no-iterator': 'warn',
        'no-label-var': 'warn',
        'no-labels': ['warn', { allowLoop: true, allowSwitch: false }],
        'no-lone-blocks': 'warn',
        'no-loop-func': 'warn',
        'no-multi-str': 'warn',
        'no-new-func': 'warn',
        'no-new-wrappers': 'warn',
        'no-obj-calls': 'warn',
        'no-redeclare': 'warn',
        'no-regex-spaces': 'warn',
        'no-script-url': 'warn',
        'no-self-assign': 'warn',
        'no-self-compare': 'warn',
        'no-sequences': 'warn',
        'no-shadow-restricted-names': 'warn',
        'no-sparse-arrays': 'warn',
        'no-template-curly-in-string': 'warn',
        'no-this-before-super': 'warn',
        'no-throw-literal': 'warn',
        'no-restricted-globals': [
          'error',
          'addEventListener',
          'blur',
          'close',
          'closed',
          'confirm',
          'defaultStatus',
          'defaultstatus',
          'event',
          'external',
          'find',
          'focus',
          'frameElement',
          'frames',
          'history',
          'innerHeight',
          'innerWidth',
          'length',
          'location',
          'locationbar',
          'menubar',
          'moveBy',
          'moveTo',
          'name',
          'onblur',
          'onerror',
          'onfocus',
          'onload',
          'onresize',
          'onunload',
          'open',
          'opener',
          'opera',
          'outerHeight',
          'outerWidth',
          'pageXOffset',
          'pageYOffset',
          'parent',
          'print',
          'removeEventListener',
          'resizeBy',
          'resizeTo',
          'screen',
          'screenLeft',
          'screenTop',
          'screenX',
          'screenY',
          'scroll',
          'scrollbars',
          'scrollBy',
          'scrollTo',
          'scrollX',
          'scrollY',
          'self',
          'status',
          'statusbar',
          'stop',
          'toolbar',
          'top',
        ],
        'no-unexpected-multiline': 'warn',
        'no-unreachable': 'warn',
        'no-unused-expressions': [
          'error',
          { allowShortCircuit: true, allowTernary: true, allowTaggedTemplates: true },
        ],
        'no-unused-labels': 'warn',
        'no-useless-computed-key': 'warn',
        'no-useless-concat': 'warn',
        'no-useless-escape': 'warn',
        'no-useless-rename': [
          'warn',
          { ignoreDestructuring: false, ignoreImport: false, ignoreExport: false },
        ],
        'no-with': 'warn',
        'require-yield': 'warn',
        'unicode-bom': ['warn', 'never'],
        'use-isnan': 'warn',
        'valid-typeof': 'warn',
        'no-restricted-properties': [
          'error',
          {
            object: 'require',
            property: 'ensure',
            message:
              'Please use import() instead. More info: https://facebook.github.io/create-react-app/docs/code-splitting',
          },
          {
            object: 'System',
            property: 'import',
            message:
              'Please use import() instead. More info: https://facebook.github.io/create-react-app/docs/code-splitting',
          },
        ],
        'getter-return': 'warn',
        'import/first': 'error',
        'import/no-amd': 'error',
        'import/no-webpack-loader-syntax': 'error',
        'default-case': 'off',
        'no-dupe-class-members': 'off',
        'no-array-constructor': 'warn',
        'no-use-before-define': [
          'warn',
          { functions: false, classes: false, variables: false, typedefs: false },
        ],
        'no-unused-vars': ['warn', { args: 'none', ignoreRestSiblings: true }],
        'no-useless-constructor': 'warn',
        'typescript/no-namespace': 'error',
        'react/rules-of-hooks': 'error',
        'react/exhaustive-deps': 'warn',
        'react/static-components': 'error',
        'react/use-memo': 'error',
        'react/preserve-manual-memoization': 'error',
        'react/incompatible-library': 'warn',
        'react/immutability': 'error',
        'react/globals': 'error',
        'react/refs': 'error',
        'react/set-state-in-effect': 'error',
        'react/error-boundaries': 'error',
        'react/purity': 'error',
        'react/set-state-in-render': 'error',
        'react/unsupported-syntax': 'warn',
        'react/jsx-no-comment-textnodes': 'warn',
        'react/jsx-no-duplicate-props': 'warn',
        'react/jsx-no-target-blank': 'warn',
        'react/jsx-no-undef': 'error',
        'react/jsx-pascal-case': ['warn', { allowAllCaps: true, ignore: [] }],
        'react/no-danger-with-children': 'warn',
        'react/no-direct-mutation-state': 'warn',
        'react/no-is-mounted': 'warn',
        'react/react-in-jsx-scope': 'off',
        'react/style-prop-object': 'warn',
        'react/jsx-no-useless-fragment': 'warn',
        'jsx-a11y/alt-text': 'warn',
        'jsx-a11y/anchor-has-content': 'warn',
        'jsx-a11y/anchor-is-valid': ['warn', { aspects: ['noHref', 'invalidHref'] }],
        'jsx-a11y/aria-activedescendant-has-tabindex': 'warn',
        'jsx-a11y/aria-props': 'warn',
        'jsx-a11y/aria-proptypes': 'warn',
        'jsx-a11y/aria-role': 'warn',
        'jsx-a11y/aria-unsupported-elements': 'warn',
        'jsx-a11y/heading-has-content': 'warn',
        'jsx-a11y/iframe-has-title': 'warn',
        'jsx-a11y/img-redundant-alt': 'warn',
        'jsx-a11y/no-access-key': 'warn',
        'jsx-a11y/no-distracting-elements': 'warn',
        'jsx-a11y/no-redundant-roles': 'warn',
        'jsx-a11y/role-has-required-aria-props': 'warn',
        'jsx-a11y/role-supports-aria-props': 'warn',
        'jsx-a11y/scope': 'warn',
      },
    },

    // Previously provided by `eslint-plugin-storybook` `flat/recommended`
    {
      files: ['**/*.stories.{ts,tsx,js,jsx,mjs,cjs}', '**/*.story.{ts,tsx,js,jsx,mjs,cjs}'],
      plugins: ['react', 'import'],
      jsPlugins: ['eslint-plugin-storybook'],
      rules: {
        'storybook/await-interactions': 'error',
        'storybook/context-in-play-function': 'error',
        'storybook/default-exports': 'error',
        'storybook/hierarchy-separator': 'warn',
        'storybook/no-redundant-story-name': 'warn',
        'storybook/no-renderer-packages': 'error',
        'storybook/prefer-pascal-case': 'warn',
        'storybook/story-exports': 'error',
        'storybook/use-storybook-expect': 'error',
        'storybook/use-storybook-testing-library': 'error',
        'import/no-anonymous-default-export': 'off',
        'react/rules-of-hooks': 'off',
      },
    },
    {
      files: ['.storybook/main.{js,cjs,mjs,ts}'],
      jsPlugins: ['eslint-plugin-storybook'],
      rules: {
        // Absolute path, since the rule otherwise resolves package.json from the cwd
        'storybook/no-uninstalled-addons': [
          'error',
          { packageJsonLocation: fileURLToPath(new URL('./package.json', import.meta.url)) },
        ],
      },
    },

    ...baseOverrides,

    // TypeScript specific rules
    {
      files: ['**/*.{ts,tsx}'],
      plugins: ['typescript', 'react'],
      // import/order is not implemented natively in oxlint, so it runs through the
      // ESLint plugin. The alias is required since `import` is a native plugin name.
      jsPlugins: [{ name: 'import-js', specifier: 'eslint-plugin-import' }],
      rules: {
        'typescript/consistent-type-exports': 'error',
        'typescript/consistent-type-imports': 'error',
        'no-redeclare': 'off',
        'no-restricted-imports': ['error', { patterns: commonRestrictedImports }],
        'import-js/order': [
          'error',
          {
            ...importOrderRules,
            pathGroups: [
              ...importOrderRules.pathGroups,
              { pattern: '.storybook/**', group: 'internal' },
            ],
          },
        ],
        'react/forward-ref-uses-ref': 'error',
      },
    },

    // TypeScript-specific barrel file restrictions
    {
      files: ['**/*.{ts,tsx}'],
      rules: {
        'no-restricted-imports': [
          'error',
          {
            patterns: [
              ...commonRestrictedImports,
              {
                regex: '^((src|\\.{1,2})\\/)((\\.{1,2}\\/)|\\w+\\/)*(alpha|beta|stable)',
                message: 'Do not import from barrel files.',
              },
            ],
          },
        ],
      },
    },
    // The barrel files themselves may import from other barrel files
    {
      files: ['src/alpha.ts', 'src/beta.ts', 'src/stable.ts'],
      rules: {
        'no-restricted-imports': ['error', { patterns: commonRestrictedImports }],
      },
    },
  ],
});
