name: Publish to Chromatic

on:
  workflow_run:
    workflows: ["Build"]
    types:
      - completed

permissions:
  contents: read

jobs:
  setup:
    uses: ./.github/workflows/setup.yml
  chromatic:
    runs-on: ubuntu-latest
    needs: setup
    if: ${{ github.event.workflow_run.conclusion == 'success' }}
    steps:
      - name: Publish Storybook to Chromatic
        uses: chromaui/action@v13
        with:
          projectToken: ${{ secrets.CHROMATIC_PROJECT_TOKEN }}
          workingDir: '@kv-designsystem/react'
          exitZeroOnChanges: true
          exitOnceUploaded: true
          onlyChanged: true
          externals: 'design-tokens/src/**'
